name: seminar_GISOVA

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pip
  - qgis=3.40
  # interactive notebooks
  - jupyter
  - nbformat
  # Data processing libs
  - scipy
  - geopandas
  - pygeoda
  # Python packages for Python checks
  - black 
  - isort
  - mypy
  - pep8
  - flake8
  - pylint
  # SQL
  - psycopg
  # install from pip
  - pip:
    # pyqt5 stubs to support pyqt5 in mypy and typing 
    - pyqt5-stubs
  # cuda
  # - cudatoolkit
  # - cuda-version=11
  