name: Render presentation

on: 
  push:
    paths:
      - '**.qmd'
      - '.github/workflows/render_presentation.yaml'

jobs:

  render:

    runs-on: ubuntu-22.04

    permissions:
      contents: write
    
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Render Quarto
        run: quarto render --output-dir prezentace --self-contained prezentace.qmd
      
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add prezentace/
          git commit -m 'Render presentation'
          git push